{...}: {
  imports = [
    ./gtk.nix
    ./btop.nix
    ./neovim.nix
    ./kitty.nix
    ./discord.nix
    ./bat.nix
    ./firefox.nix
    ./picom.nix
    ./zathura.nix
    ./tmux.nix
    ./mpv.nix
    ./awesomewm.nix
    ./alacritty.nix
    ./ncmpcpp.nix
    ./mpd.nix
    ./nnn.nix
    ./git
    ./fish
    ./rofi
    ./zellij.nix
    ./gh.nix
    ./pkgs.nix
    ./wezterm.nix
    ./scripts.nix
    ./yazi.nix
    ./ghostty.nix
  ];
}
